server:
  port: 8025
spring:
  profiles:
    active: test
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:auto-parts-web-dev-test
---
spring:
  config:
    activate:
      on-profile: prod-postgres
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/auto-parts-web-dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop