insert into tb_category (name, type) values ('Partes Externas', 'OUTSIDE_VEHICLE');
insert into tb_category (name, type) values ('Partes Internas', 'INSIDE_VEHICLE');
insert into tb_category (name, type) values ('Diversas', 'MISCELLANEOUS');
insert into tb_category (name, type) values ('Partes Mecanicas', 'MECHANICAL_PARTS');
insert into tb_category (name, type) values ('Tunagem', 'TUNING_PARTS');

insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 1','Descrição do produto 1', 270.0, 0.5, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 2','Descrição do produto 2', 100.0, 0.3, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 3','Descrição do produto 3', 320.0, 0.2, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 4','Descrição do produto 4', 599.9, 0, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 5','Descrição do produto 5', 1500.2, 0.8, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 6', 'Descrição do produto 6', 200.0, 0.1, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 7', 'Descrição do produto 7', 450.0, 0.4, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 8', 'Descrição do produto 8', 80.0, 0.2, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 9', 'Descrição do produto 9', 150.0, 0.1, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 10', 'Descrição do produto 10', 280.0, 0.3, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 11', 'Descrição do produto 11', 400.0, 0.2, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 12', 'Descrição do produto 12', 700.0, 0.5, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 13', 'Descrição do produto 13', 350.0, 0.3, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 14', 'Descrição do produto 14', 1200.0, 0.4, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 15', 'Descrição do produto 15', 180.0, 0.1, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 16', 'Descrição do produto 16', 220.0, 0.15, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 17', 'Descrição do produto 17', 180.0, 0.2, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 18', 'Descrição do produto 18', 120.0, 0.1, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 19', 'Descrição do produto 19', 250.0, 0.3, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 20', 'Descrição do produto 20', 300.0, 0.25, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 21', 'Descrição do produto 21', 280.0, 0.15, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 22', 'Descrição do produto 22', 500.0, 0.4, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 23', 'Descrição do produto 23', 420.0, 0.35, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 24', 'Descrição do produto 24', 800.0, 0.5, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 25', 'Descrição do produto 25', 620.0, 0.4, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 26', 'Descrição do produto 26', 240.0, 0.2, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 27', 'Descrição do produto 27', 190.0, 0.15, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 28', 'Descrição do produto 28', 110.0, 0.1, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 29', 'Descrição do produto 29', 280.0, 0.25, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 30', 'Descrição do produto 30', 340.0, 0.3, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 31', 'Descrição do produto 31', 310.0, 0.2, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 32', 'Descrição do produto 32', 620.0, 0.4, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 33', 'Descrição do produto 33', 480.0, 0.35, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 34', 'Descrição do produto 34', 950.0, 0.5, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 35', 'Descrição do produto 35', 720.0, 0.4, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 36', 'Descrição do produto 36', 260.0, 0.2, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 37', 'Descrição do produto 37', 210.0, 0.15, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 38', 'Descrição do produto 38', 100.0, 0.1, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 39', 'Descrição do produto 39', 230.0, 0.25, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 40', 'Descrição do produto 40', 310.0, 0.3, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 41', 'Descrição do produto 41', 280.0, 0.2, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 42', 'Descrição do produto 42', 540.0, 0.4, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 43', 'Descrição do produto 43', 420.0, 0.35, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 44', 'Descrição do produto 44', 920.0, 0.5, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 45', 'Descrição do produto 45', 720.0, 0.4, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 46', 'Descrição do produto 46', 280.0, 0.2, '', 1);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 47', 'Descrição do produto 47', 130.0, 0.1, '', 2);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 48', 'Descrição do produto 48', 360.0, 0.3, '', 3);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 49', 'Descrição do produto 49', 620.0, 0.4, '', 4);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 50', 'Descrição do produto 50', 1100.0, 0.5, '', 5);
insert into tb_product (name, description, price, discount, image, category_id) values ('Produto 51', 'Descrição do produto 51', 1100.0, 0.5, '', 5);

INSERT INTO tb_user (name, email, password, birth_date, gender, cpf, phone) VALUES ('Marcos Felipe Altenhofen', 'm.felipealt@gmail.com', '$2a$10$8hEEfl7XZD8GOA33OsZGy.Fpjo20ufQ5rhlcxZJDt1tjid2d4WQiy', '2003-09-18 21:00:00', 'male', '104.381.109-51', '46991077717');
